apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
- path: manifests/patches/prometheus-ClusterRole.yaml
- path: manifests/patches/prometheus-prometheus.yaml
- path: manifests/patches/alertmanager-secret.secret.yaml
- path: manifests/patches/alertmanager-alertmanager.yaml
# - path: manifests/patches/grafana-deployment.yaml

resources:
- manifests/upstream
- manifests/monitoring.ingress.yaml
- manifests/kube-controller-manager-prometheus-discovery.service.yaml
- manifests/kube-scheduler-prometheus-discovery.service.yaml
