apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  name: acceptall
  namespace: linkerd-viz
spec:
  client:
    unauthenticated: true
    networks:
    - cidr: 0.0.0.0/0
  server:
    selector:
      matchLabels: {}
