apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: natsio

commonLabels:
  app.kubernetes.io/part-of: nats
  app.kubernetes.io/component: queue
resources:
- jetstream/
- jetstream-controller/
