apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: elastic-system
resources:
- manifests/upstream
configMapGenerator:
- files:
  - manifests/configs/eck.yaml
  name: elastic-operator
  behavior: replace
  namespace: elastic-system
