apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/name: pyrra-api
    app.kubernetes.io/part-of: pyrra
  name: pyrra
spec:
  endpoints:
  - interval: 15s
    port: http
  selector:
    matchLabels:
      app.kubernetes.io/component: monitoring
      app.kubernetes.io/name: pyrra-api
      app.kubernetes.io/part-of: pyrra
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/name: pyrra-kubernetes
    app.kubernetes.io/part-of: pyrra
  name: pyrra-kubernetes
spec:
  endpoints:
  - interval: 15s
    port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/component: monitoring
      app.kubernetes.io/name: pyrra-kubernetes
      app.kubernetes.io/part-of: pyrra
