apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: jetstream-controller
  app.kubernetes.io/version: 0.5.0
resources:
- manifests/crds.yaml
- manifests/deployment.yaml
- manifests/rbac.yaml

images:
- name: natsio/jetstream-controller
  newTag: 0.5.0

