apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/upstream/linkerd.aio.yaml

patches:
  - path: manifests/patches/identity.yaml
  - path: manifests/patches/destination.yaml
