apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: loki

commonLabels:
  app.kubernetes.io/part-of: loki
  app.kubernetes.io/component: logging

resources:
- manifests/namespace.yaml
- manifests/promtail.yaml
