apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: localpv
configMapGenerator:
- files:
  - manifests/configs/config.json
  - manifests/configs/setup
  - manifests/configs/teardown
  - manifests/configs/helperPod.yaml
  name: local-path-config
  options:
    disableNameSuffixHash: true

resources:
- manifests/localpv.deploy.yaml
- manifests/localpv.roles.yaml
- manifests/localpv.sa.yaml
- manifests/localpv.sc.yaml
