- op: add
  path: /spec/template/spec/containers/0/volumeMounts/0
  value:
    name: "git-crypt-dev-key"
    mountPath: "/etc/git-crypt"
- op: add
  path: /spec/template/spec/volumes/0
  value:
    name: "git-crypt-dev-key"
    secret:
      secretName: "git-crypt-dev-key"
- op: replace
  path: /spec/template/spec/automountServiceAccountToken
  value: true
- op: add
  path: /spec/template/spec/serviceAccountName
  value: argocd-server
