apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: postgres-operator

secretGenerator:
- envs:
  - manifests/secrets/pg-env.secret.conf
  name: pg-env
  options:
    disableNameSuffixHash: true
  type: Opaque
configMapGenerator:
- envs:
  - manifests/configs/pg-env.conf
  name: pg-env
  options:
    disableNameSuffixHash: true
