apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grafana

commonLabels:
  app.kubernetes.io/part-of: grafana
  app.kubernetes.io/component: grafana

resources:
- manifests/grafana-dashboardDefinitions.yaml
- manifests/grafana-deployment.yaml
- manifests/grafana-service.yaml
- manifests/grafana-serviceAccount.yaml
- manifests/grafana-serviceMonitor.yaml
- manifests/grafana.ingress.yaml
#- manifests/grafana.ns.yaml
- manifests/grafana-db.yaml

configMapGenerator:
- files:
  - manifests/configs/dashboards.yaml
  name: grafana-dashboards
- files:
  - manifests/configs/grafana.config.ini
  name: grafana-config
secretGenerator:
- files:
  - manifests/secrets/datasources.yaml
  name: grafana-datasources
  type: Opaque
images:
  - name: grafana/grafana
    newTag: 9.1.0
