apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
spec:
  endpoints:
  - interval: 15s
    port: metrics
  selector:
    matchLabels:
      k8s-app: oauth2-proxy
