apiVersion: pyrra.dev/v1alpha1
kind: ServiceLevelObjective
metadata:
  labels:
    pyrra.dev/team: dex
  name: dex-http-errors
spec:
  description: |
    Dex should successfullly handle http requests in 99.95% of all cases.
  alerting:
    name: DexHTTPErrorBudgetBurn
  indicator:
    ratio:
      grouping:
      - handler
      - method
      errors:
        metric: http_requests_total{service="dex",code=~"5.."}
      total:
        metric: http_requests_total{service="dex"}
  target: "99.95"
  window: 2w
