apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: micros-stg
resources:
  - manifests/backup-redis.cronjob.yaml
secretGenerator:
- files:
  - manifests/secrets/config.json
  name: mc-config
  type: Opaque
configMapGenerator:
- literals:
  - CLUSTER_NAME=scaleway-b
  - S3_BUCKET=micros-backups
  name: redis-backup
