apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

commonLabels:
  app.kubernetes.io/part-of: pyrra
  app.kubernetes.io/component: monitoring

resources:
- manifests/upstream/pyrra.dev_servicelevelobjectives.yaml
- manifests/upstream/role.yaml
- manifests/upstream/api.yaml
- manifests/upstream/kubernetes.yaml
- manifests/ingress.yaml
- manifests/svc-monitor.yaml


patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/ports
      value:
        - name: metrics
          containerPort: 8080
  target:
    kind: Deployment
    name: pyrra-kubernetes
- patch: |-
    - op: add
      path: /spec/ports/2
      value:
        name: metrics
        port: 8080
  target:
    kind: Service
    name: pyrra-kubernetes
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: 250M
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: 50M
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: 200m
  target:
    kind: Deployment
    name: pyrra-api
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: 250M
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: 50M
    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: 200m
  target:
    kind: Deployment
    name: pyrra-kubernetes
images:
- name: ghcr.io/pyrra-dev/pyrra
  newTag: pr-449
