apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: _NAME_
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: micros-infra
  source:
    path: envs/_PATH_
    plugin:
      name: kustomize-gcrypt
    repoURL: 'https://github.com/microspray/deployments-infra.git'
    targetRevision: HEAD
  syncPolicy:
    automated: {}
