apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nats
spec:
  endpoints:
  - interval: 15s
    port: metrics
    path: /metrics
  selector:
    matchLabels:
      app.kubernetes.io/component: queue
      app.kubernetes.io/name: jetstream
      app.kubernetes.io/part-of: nats
