apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9153"
    prometheus.io/scrape: "true"
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    k8s-app: nodelocaldns
    app.kubernetes.io/name: nodelocaldns
  name: nodelocaldns
  namespace: kube-system
spec:
  ports:
  - name: dns
    port: 53
    protocol: UDP
    targetPort: 53
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: 53
  - name: metrics
    port: 9253
    protocol: TCP
    targetPort: 9253
  selector:
    app.kubernetes.io/name: nodelocaldns
  type: ClusterIP
