apiVersion: v1
items:
- apiVersion: cilium.io/v2
  kind: CiliumLocalRedirectPolicy
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"cilium.io/v2","kind":"CiliumLocalRedirectPolicy","metadata":{"annotations":{},"name":"nodelocaldns","namespace":"kube-system"},"spec":{"redirectBackend":{"localEndpointSelector":{"matchLabels":{"k8s-app":"nodelocaldns"}},"toPorts":[{"name":"dns","port":"53","protocol":"UDP"},{"name":"dns-tcp","port":"53","protocol":"TCP"}]},"redirectFrontend":{"serviceMatcher":{"namespace":"kube-system","serviceName":"coredns"}}}}
    creationTimestamp: "2021-10-05T10:24:21Z"
    generation: 1
    name: nodelocaldns
    namespace: kube-system
    resourceVersion: "57234891"
    uid: 19e25855-f868-47c5-9e1a-ac06f29e5731
  spec:
    redirectBackend:
      localEndpointSelector:
        matchLabels:
          k8s-app: nodelocaldns
      toPorts:
      - name: dns
        port: "53"
        protocol: UDP
      - name: dns-tcp
        port: "53"
        protocol: TCP
    redirectFrontend:
      serviceMatcher:
        namespace: kube-system
        serviceName: coredns
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
