apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  labels:
    cluster-name: cluster-1
  name: micros-infra
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: micros-infra
  source:
    path: argocd/cluster-1
    plugin:
      name: kustomize-gcrypt
    repoURL: 'https://github.com/microspray/deployments-infra.git'
    targetRevision: HEAD
  syncPolicy:
    automated: {}
