apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: k8s-auth
  name: k8s-auth
  namespace: dex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-auth
  template:
    metadata:
      labels:
        app: k8s-auth
    spec:
      containers:
      - image: mintel/dex-k8s-authenticator:1.4.0
        name: k8s-auth
        args:
          - --config
          - /etc/k8s-auth/config.yaml
        ports:
        - name: http
          containerPort: 5556
        volumeMounts:
        - name: config
          mountPath: /etc/k8s-auth
      volumes:
      - name: config
        configMap:
          name: k8s-auth-config
          items:
          - key: config.yaml
            path: config.yaml
