apiVersion: apps/v1
kind: Deployment
metadata:
  name: jetstream-controller
spec:
  replicas: 1
  template:
    spec:
      serviceAccountName: jetstream-controller
      containers:
      - name: jsc
        image: natsio/jetstream-controller
        imagePullPolicy: IfNotPresent
        command:
        - /jetstream-controller
        - -s=nats://nats:4222
        resources:
          requests:
            memory: "8Mi"
            cpu: "5m"
