apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
- manifests/pgadmin.ingress.yaml
- manifests/pgadmin.aio.yaml
namespace: pgadmin

secretGenerator:
- envs:
  - manifests/secrets/pgpassword.env
  name: pgadmin-password
  type: Opaque
